"""Regression: bows-throne drop page must link all 10 product cards.

The per-drop pages under scratch/<slug>/index.html are generated by
scripts/build_drop_pages.py from scratch/index.html's tiles-data. Canonical
product handles live in data/shopify_variants.json and the product pages in
product/<handle>.html — every card whose product exists must carry a usable
"u" link, and the per-drop page must not drift behind the scratch index.
"""
import json
import os
import re
import sys

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'scripts'))

from build_drop_pages import slugify  # noqa: E402

BOWS_DIR = os.path.join(ROOT, 'scratch', 'bows-throne-drop-20260906')

EXPECTED_HANDLES = {
    'bows-throne-apres-single', 'bows-throne-apres-mirror',
    'bows-throne-apres-tile', 'bows-throne-harem-brickup',
    'bows-throne-harem-tile', 'bows-throne-harem-single',
    'bows-throne-hoop-full', 'bows-throne-hoop-half',
    'bows-throne-puffer-single', 'bows-throne-bookpack',
}


def tiles_of(path):
    html = open(path, encoding='utf-8').read()
    m = re.search(
        r'<script type="application/json" id="tiles-data">(.*?)</script>',
        html, re.S)
    assert m, f'tiles-data block missing in {path}'
    return json.loads(m.group(1))


@pytest.fixture(scope='module')
def variants():
    data = json.loads(open(
        os.path.join(ROOT, 'data', 'shopify_variants.json'),
        encoding='utf-8').read())
    return data['products']


def test_canonical_handles_exist(variants):
    assert EXPECTED_HANDLES <= set(variants), (
        sorted(EXPECTED_HANDLES - set(variants)))


def test_bows_throne_page_links_all_ten_cards(variants):
    tiles = tiles_of(os.path.join(BOWS_DIR, 'index.html'))
    assert len(tiles) == 10, f'expected 10 cards, got {len(tiles)}'
    missing = [t['t'] for t in tiles if not t.get('u')]
    assert not missing, (
        f'{len(missing)} bows-throne cards have no product link: {missing}')
    # every link must resolve to a real product page in the local tree
    seen = set()
    for t in tiles:
        m = re.fullmatch(r'/product/([a-z0-9-]+)\.html', t['u'])
        assert m, f'card {t["t"]!r} has non-product link {t["u"]!r}'
        handle = m.group(1)
        assert handle in variants, f'{handle} not in shopify_variants.json'
        assert os.path.isfile(os.path.join(ROOT, 'product', f'{handle}.html')), (
            f'product page missing for {handle}')
        seen.add(handle)
    assert seen == EXPECTED_HANDLES, (
        f'missing={sorted(EXPECTED_HANDLES - seen)} '
        f'extra={sorted(seen - EXPECTED_HANDLES)}')


def test_drop_pages_not_behind_scratch_index():
    """Per-drop pages must carry every product link their scratch-index row
    has — a regenerate must never serve fewer links than the index."""
    rows = tiles_of(os.path.join(ROOT, 'scratch', 'index.html'))['rows']
    stale = []
    for row in rows:
        href = row.get('href') or ''
        page = os.path.join(ROOT, 'scratch', href, 'index.html')
        if not href or not os.path.isfile(page):
            continue
        page_u = {t.get('t'): t.get('u') for t in tiles_of(page)}
        for t in row.get('tiles', []):
            if t.get('u') and not page_u.get(t.get('t')):
                stale.append(f'{href}{t.get("t")!r}')
    assert not stale, f'per-drop pages missing links present in index: {stale}'


def test_generator_backfills_canonical_links(tmp_path, variants):
    """A rerun of build_drop_pages logic must FILL missing links from
    canonical handles, not erase or preserve gaps."""
    from build_drop_pages import backfill_tile_links
    tiles = [
        {'t': 'bows throne Hoop Full', 'y': '$80', 'f': 'x.jpg', 'u': ''},
        {'t': 'bows throne Bookpack', 'y': '$100', 'f': 'x.jpg'},
        {'t': 'not a real product', 'y': '$1', 'f': 'x.jpg', 'u': ''},
        {'t': 'bows throne Apres Single', 'y': '$120', 'f': 'x.jpg',
         'u': '/product/bows-throne-apres-single.html'},
    ]
    filled = backfill_tile_links(tiles, variants)
    assert filled == 2
    assert tiles[0]['u'] == '/product/bows-throne-hoop-full.html'
    assert tiles[1]['u'] == '/product/bows-throne-bookpack.html'
    assert not tiles[2].get('u'), 'must not invent links for unknown products'
    assert tiles[3]['u'] == '/product/bows-throne-apres-single.html', \
        'must never overwrite an existing link'
