<?php return [
  ['name' => 'Cercle', 'kind' => 'venue', 'lede' => 'Cercle is the French word for circle. It can refer to several different entities, including administrative divisions in Mali and the French Overseas Empire, a Belgian football club, a foreign policy think-tank, a French music company, and student societies in Belgium.', 'url' => '/s/cercle-20260724-31dfa4/', 'thumb' => '/s/cercle-20260724-31dfa4/lead.png', 'date' => '2026-07-24'],
  ['name' => '30 for 30', 'kind' => 'concept', 'lede' => '30 for 30 is a sports documentary film series airing on ESPN, its sister networks, and online. The series highlights interesting people and events in sports history.', 'url' => '/s/30-for-30-20260724-c90e05/', 'thumb' => '', 'date' => '2026-07-24'],
  ['name' => 'jazz canon', 'kind' => 'concept', 'lede' => 'The jazz canon, often referred to as the Great American Songbook, is a loosely defined collection of significant 20th-century American jazz standards, popular songs, and show tunes. It comprises influential American popular songs and jazz standards from the early 20th century tha', 'url' => '/s/jazz-canon-20260724-f17d29/', 'thumb' => '/s/jazz-canon-20260724-f17d29/lead.jpg', 'date' => '2026-07-24'],
  ['name' => 'Avalon Norwood', 'kind' => 'venue', 'lede' => 'Avalon Norwood is a residential community in Norwood, Massachusetts, offering one-, two-, and three-bedroom apartments and townhomes for lease. It is managed by AvalonBay Communities.', 'url' => '/s/avalon-norwood-20260720-8c8b8a/', 'thumb' => '', 'date' => '2026-07-20'],
  ['name' => 'Music in film on screen', 'kind' => 'concept', 'lede' => 'concept researched 2026-07-05.', 'url' => '/s/music-in-film-on-screen-20260705-6a2e9a/', 'thumb' => '', 'date' => '2026-07-05'],
  ['name' => 'Toyota 4Runner', 'kind' => 'concept', 'lede' => 'concept researched 2026-07-05.', 'url' => '/s/toyota-4runner-20260705-96c59d/', 'thumb' => '/s/toyota-4runner-20260705-96c59d/lead.jpg', 'date' => '2026-07-05'],
  ['name' => 'Great Woods', 'kind' => 'concept', 'lede' => 'concept researched 2026-05-24.', 'url' => '/s/great-woods-20260524-099a1d/', 'thumb' => '/s/great-woods-20260524-099a1d/lead.jpg', 'date' => '2026-05-24'],
  ['name' => 'German History', 'kind' => 'video', 'lede' => 'The video discusses the concept of a \'big lie\' regarding history and genealogy, specifically focusing on the history of Black people and whether they are indigenous to the Americas. The speaker argues that Americans are systematically lied to about their true history, and thes el', 'url' => '/s/german-history-20260720-829771/', 'thumb' => '/s/german-history-20260720-829771/lead.jpg', 'date' => ''],
  ['name' => 'MICROSOFT OPEN-SOURCED SELF-EVOLVING AGENT SKILLS SkillOpt…', 'kind' => 'video', 'lede' => 'Microsoft has open-sourced SkillOpt, a framework for self-evolving agent skills. It allows AI agents to improve their own instructions and prompts through an iterative process of execution, evaluation, and optimization, removing the necessity for manual prompt engineering. This i', 'url' => '/s/microsoft-open-sourced-self-evolving-agent-skill-20260724-4381a7/', 'thumb' => '/s/microsoft-open-sourced-self-evolving-agent-skill-20260724-4381a7/lead.jpg', 'date' => '']
];
